spring:
  session:
    timeout: 1800
   datasource:
     url: jdbc:h2:mem:clientedb
     username: sa
     password: 
     driver-class-name: org.h2.Driver
   h2:
     console:
       enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true