apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cliente
  name: cadastrocliente
  labels:
    app: cadastrocliente
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cadastrocliente
  template:
    metadata:
      name: cadastrocliente
      labels:
        app: cadastrocliente
    spec:
      containers:
        - image: jonesparanhos/cadastrocliente:latest
          name: cadastrocliente
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 6
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 10
            failureThreshold: 5
            successThreshold: 1



