apiVersion: v1
kind: Service
metadata:
  name: cadastrocliente-svc
  namespace: cliente
spec:
  type: NodePort
  selector:
    app: cadastrocliente
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30010
  