apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: cliente
  labels:
    database: postgres
spec:
  type: ClusterIP
  selector:
    database: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
