apiVersion: v1
kind: Service
metadata:
  name: postgres-monitor-svc
  namespace: cliente
spec:
  type: ClusterIP
  selector:
    database: postgres
  ports:
    - protocol: TCP
      port: 9187
      targetPort: 9187
