apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
  labels:
    name: prometheus-configmap
  namespace: cliente
data:
  prometheus.yml:  |-
    global:
      scrape_interval: 20s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]
            labels:
              app: "prometheus"
      - job_name: "cadastrocliente"
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: ["host.docker.internal:30010"]
            labels:
              app: "cadastrocliente"
      - job_name: "redis"
        static_configs:
          - targets: ["redis-monitor-svc:9121"]
            labels:
              monitor: redis-monitor-svc
      - job_name: "postgres"
        static_configs:
          - targets: ["postgres-monitor-svc:9187"]
            labels:
              database: "postgres-monitor"