apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: cliente
  name: prometheus-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Mi
  storageClassName: standard
  