apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: cliente
  name: prometheus-pv
spec:
  storageClassName: standard
  capacity:
    storage: 300Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /run/desktop/mnt/host/c/Users/Jones/Desktop/c/Projeto 2/prometheus-pv
    type: DirectoryOrCreate