apiVersion: v1
kind: Service
metadata:
  namespace: cliente
  name: redis-monitor-svc
  labels:
    monitor: redis-monitor-svc
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 9121
      targetPort: 9121
  type: ClusterIP