apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cadastro
spec:
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /run/desktop/mnt/host/c/Users/Jones/Desktop/c/Projeto 2/docker/pv