apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: cliente
  name: postgres-pv
spec:
  capacity:
    storage: 300Mi
  storageClassName: local-storage 
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/c/Users/Jones/Desktop/c/Projeto 2/k8s/data
    type: DirectoryOrCreate