apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: cliente
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
  storageClassName: local-storage 