apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: cliente
  labels:
    app: grafana-svc
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30011
