name: Deploy2Prod
on:
  push:
    branches:
      - "main"
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.8.2'
      - name: Exibir Envs
        run: |
          java -version
          mvn -version
      - name: Clean
        run: mvn clean
        working-directory: ./workspace/CadastroCliente
      #- name: Executar testes
      #  run: mvn test
      #  working-directory: ./workspace/CadastroCliente
      - name: Incrementar Versao
        run: |
          current=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Versão atual: $current"

          IFS=. read major minor patch <<< "$current"
          new_major=$((major + 1))
          next="$new_major.$minor.$patch"
          echo "Nova versão: $next"

          mvn versions:set -DnewVersion=$next

          echo "new_version=$next" >> "$GITHUB_OUTPUT"
          shell: bash

      - name: Build
        run: mvn package -DskipTests
        working-directory: ./workspace/CadastroCliente
