name: Deploy2Prod
on:
  push:
    branches:
      - "main"
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Setup Maven Action
        uses: uses: s4u/setup-maven-action@1.18.0
        with:
          java-distribution: temurin
          java-version: 21
          maven-version: 3.9.9