name: Deploy2Prod
on:
  push:
    branches:
      - "main"
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ConfigGit
        run: |
          git config user.name "[Bot]GitHubActions"
          git config user.email "BotDevOps@teste.com"
      - name: Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.8.2'
      - name: Exibir Envs
        run: |
          java -version
          mvn -version
    
      - name: Clean
        run: mvn clean
        working-directory: ./workspace/CadastroCliente

      - name: Executar testes
        working-directory: ./workspace/CadastroCliente
        run: mvn test

      - name: Build
        run: mvn package -DskipTests
        working-directory: ./workspace/CadastroCliente

      - name: Define a versão do projeto
        run: |
          echo "PARSED_MAJOR=2" >> $GITHUB_ENV
          echo "PARSED_MINOR=5" >> $GITHUB_ENV
          echo "PROJECT_VERSION=${{ env.PARSED_MAJOR }}.${{ env.PARSED_MINOR }}" >> $GITHUB_ENV

      - name: Mostrar alteração a ser efetuada.
        run: |
          echo "PARSED_MAJOR=${{ env.PARSED_MAJOR }}"
          echo "PARSED_MINOR=${{ env.PARSED_MINOR }}"

      - name: Atualização de versão Minor
        working-directory: ./workspace/CadastroCliente/
        run: mvn --batch-mode build-helper:parse-version versions:set -DnewVersion="${parsedVersion_majorVersion}.${parsedVersion_nextMinorVersion}.0-SNAPSHOT" versions:commit

      - name: Atualização de versão Major
        working-directory: ./workspace/CadastroCliente
        run: mvn --batch-mode build-helper:parse-version versions:set -DnewVersion="${parsedVersion_nextMajorVersion}.${parsedVersion_minorVersion}.0-SNAPSHOT" versions:commit

      - name: confirmarVersao
        run: |
          echo "A versão final é teste: $($parsedVersion_majorVersion).$($parsedVersion_nextMinorVersion).0-SNAPSHOT"
      - name: Jar Copy
        working-directory: ./workspace/CadastroCliente/
        run: |
          $APP_JAR_PATH = "../../app/app.jar"
          $JAR_FILE = (Get-ChildItem target\*.jar).Name
          Write-Host "Copiando o arquivo JAR: $JAR_FILE para $APP_JAR_PATH"
          Copy-Item target\*.jar -Destination $APP_JAR_PATH

      - name: docker login
        shell: powershell
        run: |
             $password = "${{ secrets.DOCKER_TOKEN }}"
             docker login --username "${{ secrets.USER_NAME }}" --password $password


      - name: Build da imagem
        run: docker build ./app -f app/dockerfile -t cadastrocliente:${{ env.PROJECT_VERSION }} --no-cache

      - name: Criar tag
        run: docker tag cadastrocliente:${{ env.PROJECT_VERSION }} jonesparanhos/cadastrocliente:${{ env.PROJECT_VERSION }}

      - name: docker push
        run: docker push jonesparanhos/cadastrocliente:${{ env.PROJECT_VERSION }}

      - name: Criar tag latest
        run: docker tag cadastrocliente:${{ env.PROJECT_VERSION }} jonesparanhos/cadastrocliente:latest

      - name: docker push latest
        run: docker push  jonesparanhos/cadastrocliente:latest
      
      - name: Atualizando K8s
        run: kubectl rollout restart deploy cadastrocliente -n cliente

      - name: Status do deploy
        run:  kubectl rollout status deploy cadastrocliente -n cliente