name: Deploy2Prod
on:
  push:
    branches:
      - "main"
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ConfigGit
        run: |
          git config user.name "[Bot]GitHubActions"
          git config user.email "BotDevOps@teste.com"
      - name: Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.8.2'
      - name: Exibir Envs
        run: |
          java -version
          mvn -version
      - name: Clean
        run: mvn clean
        working-directory: ./workspace/CadastroCliente
      #- name: Executar testes
      #  run: mvn test
      #  working-directory: ./workspace/CadastroCliente
      - name: Build
        run: mvn package -DskipTests
        working-directory: ./workspace/CadastroCliente
     #- name: Check code version
      # echo "nova versão é": ${{steps.increment-version.new_version}}

      - name: Define a versão do projeto
        run: |
          echo "parsedVersion_majorVersion=2" >> $GITHUB_ENV
          echo "parsedVersion_nextMinorVersion=5" >> $GITHUB_ENV

      - name: Mostrar alteração a ser efetuada.
        run: |
          echo "parsedVersion_majorVersion=$parsedVersion_majorVersion"
          echo "parsedVersion_nextMinorVersion=$parsedVersion_nextMinorVersion"

      - name: Atualização de versão Minor
        working-directory: ./workspace/CadastroCliente/
        run: mvn --batch-mode build-helper:parse-version versions:set -DnewVersion="${parsedVersion_majorVersion}.${parsedVersion_nextMinorVersion}.0-SNAPSHOT" versions:commit

      - name: Atualização de versão Major
        working-directory: ./workspace/CadastroCliente
        run: mvn --batch-mode build-helper:parse-version versions:set -DnewVersion="${parsedVersion_nextMajorVersion}.${parsedVersion_minorVersion}.0-SNAPSHOT" versions:commit

      - name: confirmarVersao
        run: |
          echo "A versão final é teste: $($parsedVersion_majorVersion).$($parsedVersion_nextMinorVersion).0-SNAPSHOT"
     # - name: Commit do POM
      #  working-directory: ./workspace/CadastroCliente
       # run: |
        #    git add pom.xml
         #   git commit -m "Alterando a versão do projeto"
          #   git push origin main
      - name: Jar Copy
        working-directory: ./workspace/CadastroCliente/
        run: |
          $APP_JAR_PATH = "../../app/app.jar"
          $JAR_FILE = (Get-ChildItem target\*.jar).Name
          Write-Host "Copiando o arquivo JAR: $JAR_FILE para $APP_JAR_PATH"
          Copy-Item target\*.jar -Destination $APP_JAR_PATH

      - name: docker login
        shell: powershell
        run: |
             $password = "${{ secrets.DOCKER_TOKEN }}"
             docker login --username "${{ secrets.USER_NAME }}" --password $password


      - name: Build da imagem
        run: docker build ./app -f app/dockerfile -t cadastrocliente:5.0 --no-cache

      - name: Criar tag
        run: docker tag cadastrocliente:5.0 jonesparanhos/cadastrocliente:5.0

      - name: docker push
        run: docker push jonesparanhos/cadastrocliente:5.0

      - name: Criar tag latest
        run: docker tag cadastrocliente:5.0 jonesparanhos/cadastrocliente:latest

      - name: docker push latest
        run: docker push  jonesparanhos/cadastrocliente:latest
      
      - name: Atualizando K8s
        run: kubectl rollout restart deploy cadastrocliente -n cliente

      - name: Status do deploy
        run:  kubectl rollout status deploy cadastrocliente -n cliente
      
      
      
     # - name: Realiza o release
      #  working-directory: ./workspace/CadastroCliente
       # run: mvn --batch-mode release: clean release:prepare release:perform -Darguments="-Dmaven.javadoc.skip=true -Dmaven.test.skipTests=true -Dmaven.test.skip=true" -Dusername=${{ secrets.USERNAME }} -Dpassword=${{ secrets.PASSWORD }}

